// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpz1eii3LK8SK8yHNvnTcWor-yED3G_hc',
    appId: '1:638301923414:web:90b45eded73ab3509c73f7',
    messagingSenderId: '638301923414',
    projectId: 'stem-53cdc',
    authDomain: 'stem-53cdc.firebaseapp.com',
    databaseURL: 'https://stem-53cdc-default-rtdb.firebaseio.com',
    storageBucket: 'stem-53cdc.firebasestorage.app',
    measurementId: 'G-X0DQLH8Y0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGuKZazfhayGt74pi2tB4mUaZrrDX_Ktc',
    appId: '1:638301923414:android:714dd3f139d8ff149c73f7',
    messagingSenderId: '638301923414',
    projectId: 'stem-53cdc',
    databaseURL: 'https://stem-53cdc-default-rtdb.firebaseio.com',
    storageBucket: 'stem-53cdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIV0Ot36CshPQ2aPMz5zOgHxKEkY97VWk',
    appId: '1:638301923414:ios:7bc286d034fdc5569c73f7',
    messagingSenderId: '638301923414',
    projectId: 'stem-53cdc',
    databaseURL: 'https://stem-53cdc-default-rtdb.firebaseio.com',
    storageBucket: 'stem-53cdc.firebasestorage.app',
    iosBundleId: 'com.example.v2v',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIV0Ot36CshPQ2aPMz5zOgHxKEkY97VWk',
    appId: '1:638301923414:ios:7bc286d034fdc5569c73f7',
    messagingSenderId: '638301923414',
    projectId: 'stem-53cdc',
    databaseURL: 'https://stem-53cdc-default-rtdb.firebaseio.com',
    storageBucket: 'stem-53cdc.firebasestorage.app',
    iosBundleId: 'com.example.v2v',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpz1eii3LK8SK8yHNvnTcWor-yED3G_hc',
    appId: '1:638301923414:web:bb163a212cea2ba39c73f7',
    messagingSenderId: '638301923414',
    projectId: 'stem-53cdc',
    authDomain: 'stem-53cdc.firebaseapp.com',
    databaseURL: 'https://stem-53cdc-default-rtdb.firebaseio.com',
    storageBucket: 'stem-53cdc.firebasestorage.app',
    measurementId: 'G-MFD1QS3EYJ',
  );
}
